# Generated by Django 5.0.6 on 2024-06-30 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='balance_after_transaction',
        ),
    ]
