# Generated by Django 5.0.6 on 2024-06-30 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0004_remove_transaction_balance_after_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
