# Generated by Django 5.0.6 on 2024-07-01 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='banace_after_transaction',
            new_name='balance_after_transaction',
        ),
    ]
