# Generated by Django 5.0.6 on 2024-07-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_rename_odercar_borrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='boolinan',
            field=models.BooleanField(default=False),
        ),
    ]
