# Generated by Django 5.0.6 on 2024-07-02 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_bookcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookcomment',
            old_name='car',
            new_name='book',
        ),
    ]
